### ISSUE TITLE
Unable to run a story

### ISSUE THREAD

**Issue by gregkrsak** [daph/xyzzy#3]
I'm unable to complete the README instructions as listed. It does appear that the program loads the Z-Machine file; however, I'm unable to get it to run.

I'm still not experienced with Elixir, so please guide me if my environment is off. If you'd like to send me a specific, known-good Z-Machine file to try, feel free.

I'll outline what I've tried so far, below:

**Fresh clone of the repo:**

```
greg@swany-laptop:~/temp$ git clone https://github.com/daph/xyzzy.git
Cloning into 'xyzzy'...
remote: Counting objects: 350, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 350 (delta 2), reused 7 (delta 2), pack-reused 343
Receiving objects: 100% (350/350), 46.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (145/145), done.
Checking connectivity... done.
greg@swany-laptop:~/temp$ cd xyzzy/
```

**Compile:**

```
greg@swany-laptop:~/temp/xyzzy$ mix do deps.get, compile
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

All dependencies up to date
Compiling 11 files (.ex)
Generated xyzzy app
```

**Download a Z-Machine game:**

```
greg@swany-laptop:~/temp/xyzzy$ #Followed README link to IFDB; downloaded zork1.z5
greg@swany-laptop:~/temp/xyzzy$ mkdir stories
greg@swany-laptop:~/temp/xyzzy$ cp ~/Downloads/zork1.z5 stories/
```

**Start Elixir interactive environment:**

```
greg@swany-laptop:~/temp/xyzzy$ iex -S mix
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
```

**Open+run command per README instructions:**

```
iex(1)> Xyzzy.Machine.open_story("stories/zork1.z5") |> Xyzzy.Machine.run_story() 
** (exit) exited in: GenServer.call(:state_registry, {:whereis_name, %Xyzzy.Machine.State{abbr_table: 496, call_stack: [], dictionary: 15137, flags1: 0, flags2: 0, global_vars: 8817, high_mem: 20023, locals: %{}, memory: <<3, 0, 0, 88, 78, 55, 79, 5, 59, 33, 2, 176, 34, 113, 46, 83, 0, 0, 56, 52, 48, 55, 50, 54, 1, 240, 165, 198, 161, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, object_table: 688, pc: 20229, release: 88, stack: [], static_mem: 11859, version: 3}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:820: GenServer.call/3
    (elixir) lib/gen_server.ex:1015: GenServer.whereis/1
    (elixir) lib/gen_server.ex:818: GenServer.call/3
    (xyzzy) lib/xyzzy/machine/decoding.ex:26: Xyzzy.Machine.Decoding.get_opcode/1
    (xyzzy) lib/xyzzy/machine.ex:46: Xyzzy.Machine.run_story/1
```

**Just an open_story(...) call:**

```
iex(1)> Xyzzy.Machine.open_story("stories/zork1.z5")                            %Xyzzy.Machine.State{
  abbr_table: 496,
  call_stack: [],
  dictionary: 15137,
  flags1: 0,
  flags2: 0,
  global_vars: 8817,
  high_mem: 20023,
  locals: %{},
  memory: <<3, 0, 0, 88, 78, 55, 79, 5, 59, 33, 2, 176, 34, 113, 46, 83, 0, 0,
    56, 52, 48, 55, 50, 54, 1, 240, 165, 198, 161, 41, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, ...>>,
  object_table: 688,
  pc: 20229,
  release: 88,
  stack: [],
  static_mem: 11859,
  version: 3
}
```

**Another try at open+run:**

```
iex(2)> Xyzzy.Machine.open_story("stories/zork1.z5") |> Xyzzy.Machine.run_story()
** (exit) exited in: GenServer.call(:state_registry, {:whereis_name, %Xyzzy.Machine.State{abbr_table: 496, call_stack: [], dictionary: 15137, flags1: 0, flags2: 0, global_vars: 8817, high_mem: 20023, locals: %{}, memory: <<3, 0, 0, 88, 78, 55, 79, 5, 59, 33, 2, 176, 34, 113, 46, 83, 0, 0, 56, 52, 48, 55, 50, 54, 1, 240, 165, 198, 161, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>, object_table: 688, pc: 20229, release: 88, stack: [], static_mem: 11859, version: 3}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:820: GenServer.call/3
    (elixir) lib/gen_server.ex:1015: GenServer.whereis/1
    (elixir) lib/gen_server.ex:818: GenServer.call/3
    (xyzzy) lib/xyzzy/machine/decoding.ex:26: Xyzzy.Machine.Decoding.get_opcode/1
    (xyzzy) lib/xyzzy/machine.ex:46: Xyzzy.Machine.run_story/1
```

**Flailing around with a lonely call to run_story():**

```
iex(2)> Xyzzy.Machine.run_story()                                               ** (UndefinedFunctionError) function Xyzzy.Machine.run_story/0 is undefined or private. Did you mean one of:

      * run_story/1

    (xyzzy) Xyzzy.Machine.run_story()
iex(2)>
```

**Mix version check:**

```
greg@swany-laptop:~/temp/xyzzy$ mix --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.6.1 (compiled with OTP 19)
```

**Comment by daph** [comment]
yeah woops, I think I might be missing something from the instructions. I'll figure it out and update.

Also, the machine is super incomplete so story files won't actually quite run yet, but they should at least move along until an unimplemented opcode is hit.
